<!-- Start Comments -->
<div class="comments content">
	<h2>Comments</h2>
	<hr/>
	{% for comment in comments %}
	<div class="comments-box">
		<div class="row">
			<div class="col-lg-2 col-md-2 col-xs-12 col-sm-12">
				<img class="pane-author" src="http://www.gravatar.com/avatar/{{ comment.mailhash }}?s=200" title="{{ comment.name | raw }}" alt="{{ comment.name | raw }}">
			</div>
			<div class="col-lg-10 col-md-10 col-xs-12 col-sm-12 comment-content">
				<h4 class="comment-name">
				{% if comment.author_url %}
				<a href="{{ comment.author_url }}" target="_blank">{{ comment.author | raw }}</a>
				{% else %}
				{{ comment.author | raw }}
				{% endif %}
				<span>{{ comment.date|date("F jS, Y") }}</span>
				</h4>
			<div class="comment-section">
				<p>{{ comment.content | raw }} </p>
			</div>
			</div>
		</div>
	</div>
	{% else %}
	<p><em>No comments to display for this post.</em></p>
	{% endfor %}
</div>
<!-- End Comments -->

<!-- Start Comments Box -->
<div class="comments content">
	<h2>LEAVE A REPLY</h2>
	<hr/>
	<form class="comments-form form-horizontal" id="form" method="post" action="">
		<div class="row">
			<div class="col-lg-6 col-md-6 col-xs-12">
				<div class="form-group">
				<input type="text" name="author" class="form-control" placeholder="Name" value="{{ author }}" required>
				{% if AuthorError %}<span>{{ AuthorError }}</span>{% endif %}
				</div>
				<div class="form-group">
				<input type="email" name="author_email" class="form-control" placeholder="Email" value="{{ author_email }}" required>
				{% if EmailError %}<span>{{ EmailError }}</span>{% endif %}
				</div>
				<div class="form-group">
				<input type="link" name="author_url" class="form-control" placeholder="Website" value="{{ author_url }}">
				{% if URLError %}<span>{{ URLError }}</span>{% endif %}
				</div>
			</div>
			<div class="col-lg-6 col-md-6 col-xs-12">
				<div class="form-group">
				<textarea name="content" class="form-control" placeholder="Comment" required>{{ content }}</textarea>
				{% if ContentError %}<span>{{ ContentError }}</span>{% endif %}
				</div>
				<button type="submit" name="submit" id="submit" class="btn btn-paleutism pull-right">Post Comment</button>
			</div>
		</div>
	</form>
	{% if message  %}
	<h1 class="success">{{ message }}</h1>
	{% endif %}
</div>
<!-- End Comments Box -->