<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>My Topic, My Opinion - Dashboard</title>
		
	<link href="template/default/assets/css/bootstrap.min.css" rel="stylesheet">
	<link href="template/default/assets/css/bootstrap-table.css" rel="stylesheet">	
	<link href="template/default/assets/css/styles.css" rel="stylesheet">
		
	<!--Icons-->
	<script src="template/default/assets/js/lumino.glyphs.js"></script>
		
	<!--[if lt IE 9]>
	<script src="template/default/assets/js/html5shiv.js"></script>
	<script src="template/default/assets/js/respond.min.js"></script>
	<![endif]-->
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
	<div class="container-fluid">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#sidebar-collapse">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="#"><span>My Topic, My Opinion</span>Dashboard</a>
			<ul class="user-menu">
				<li class="dropdown pull-right">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown"><svg class="glyph stroked male-user"><use xlink:href="#stroked-male-user"></use></svg> {{ user }} <span class="caret"></span></a>
				<ul class="dropdown-menu" role="menu">
				<li><a href="settings.php"><svg class="glyph stroked gear"><use xlink:href="#stroked-gear"></use></svg> Settings</a></li>
				<li><a href="logout.php"><svg class="glyph stroked cancel"><use xlink:href="#stroked-cancel"></use></svg> Log Out</a></li>
				</ul></li>
			</ul>
		</div>							
	</div><!-- /.container-fluid -->
</nav>
		
<div id="sidebar-collapse" class="col-sm-3 col-lg-2 sidebar">
	<ul class="nav menu">
		<li class="active"><a href="index.php"><svg class="glyph stroked home"><use xlink:href="#stroked-home"></use></svg> Dashboard</a></li>
		<li><a href="posts.php"><svg class="glyph stroked app window with content"><use xlink:href="#stroked-app-window-with-content"></use></svg> All Posts</a></li>
		<li><a href="new-post.php"><svg class="glyph stroked pencil"><use xlink:href="#stroked-pencil"></use></svg> Add New</a></li>
		<li><a href="categories.php"><svg class="glyph stroked folder"><use xlink:href="#stroked-folder"></use></svg> Categories</a></li>
		<li><a href="comments.php"><svg class="glyph stroked empty-message"><use xlink:href="#stroked-empty-message"></use></svg> Comments</a></li>
		<li><a href="users.php"><svg class="glyph stroked male user"><use xlink:href="#stroked-male-user"></use></svg> Users</a></li>
		<li><a href="settings.php"><svg class="glyph stroked gear"><use xlink:href="#stroked-gear"></use></svg> Settings</a></li>
		<li><a href="logout.php"><svg class="glyph stroked cancel"><use xlink:href="#stroked-cancel"></use></svg> Log Out</a></li>
		<li role="presentation" class="divider"></li>
	</ul>

</div><!--/.sidebar-->
		
<div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">			
	<div class="row">
		<ol class="breadcrumb">
			<li><a href="index.php"><svg class="glyph stroked home"><use xlink:href="#stroked-home"></use></svg></a></li>
			<li class="active">Dashboard</li>
		</ol>
	</div><!--/.row-->
				
	<div class="row">
	
		<div class="col-xs-12 col-md-6 col-lg-3">
			<div class="panel panel-blue panel-widget">
				<div class="row no-padding">
					<div class="col-sm-3 col-lg-5 widget-left">
						<svg class="glyph stroked clipboard-with-paper"><use xlink:href="#stroked-clipboard-with-paper"></use></svg>
					</div>
					<div class="col-sm-9 col-lg-7 widget-right">
						<div class="large">{{ publishedposts }}</div>
						<div class="text-muted">Published</div>
					</div>
				</div>
			</div>
		</div>
		
		<div class="col-xs-12 col-md-6 col-lg-3">
			<div class="panel panel-orange panel-widget">
				<div class="row no-padding">
					<div class="col-sm-3 col-lg-5 widget-left">
						<svg class="glyph stroked blank-document"><use xlink:href="#stroked-blank-document"></use></svg>
					</div>
					<div class="col-sm-9 col-lg-7 widget-right">
						<div class="large">{{ drafts }}</div>
						<div class="text-muted">Drafts</div>
					</div>
				</div>
			</div>
		</div>
		
		<div class="col-xs-12 col-md-6 col-lg-3">
			<div class="panel panel-teal panel-widget">
				<div class="row no-padding">
					<div class="col-sm-3 col-lg-5 widget-left">
						<svg class="glyph stroked folder"><use xlink:href="#stroked-folder"></use></svg>
					</div>
					<div class="col-sm-9 col-lg-7 widget-right">
						<div class="large">{{ categoriescount }}</div>
						<div class="text-muted">Categories</div>
					</div>
				</div>
			</div>
		</div>
		
		<div class="col-xs-12 col-md-6 col-lg-3">
			<div class="panel panel-red panel-widget">
				<div class="row no-padding">
					<div class="col-sm-3 col-lg-5 widget-left">
						<svg class="glyph stroked male-user"><use xlink:href="#stroked-male-user"></use></svg>
					</div>
					<div class="col-sm-9 col-lg-7 widget-right">
						<div class="large">{{ users }}</div>
						<div class="text-muted">Users</div>
					</div>
				</div>
			</div>
		</div>

	</div><!--/.row-->

<div class="row">
		<div class="col-lg-12">
		<div class="panel panel-default">
		<div class="panel-heading">Quick Post</div>
		<div class="panel-body">
		<div class="col-md-12">
		<form role="form" enctype="multipart/form-data" action="index.php" method="post">
							
		<div class="form-group">
		<label>Post Title:</label>
		<input type="text" name="title" id="title" placeholder="Post Title" class="form-control" required="required">
		</div>
		
		<div class="form-group">
		<label>Category:</label>
		<select name="category" style="width:100%">
		{% for category in categories %}
		<option value="{{ category.id }}">{{ category.title }}</option>
	    	{% endfor %}
	    	</select>
		</div>

		<div class="form-group">
		<label>Post Description:</label>
		<textarea style="width:100%" name="description" id="description" required> </textarea>
		</div>	
		
		
		<div class="form-group">
		<label>Post Content:</label>
		<textarea style="width:100%;" name="content" id="content" required> </textarea>
		</div>
								
		<div class="form-group">
		<label>Post Photo:</label>
		<input type="file" name="photo" id="photo" class="form-control">
		</div>	
				
		<button type="submit" name="submit" class="btn btn-paleutism pull-right">Add Post</button>
		</form></div>
		

		</div>
		</div>
		</div><!-- /.col-->

		<div class="col-lg-6">
		<div class="panel panel-default">
			<div class="panel-heading">Categories</div>
				<div class="panel-body">
					<div class="col-md-12">
						<table data-toggle="table" >
						    <thead>
						    <tr>
								<th data-field="id"  data-sortable="true">ID</th> 
								<th data-field="username" data-sortable="true">Title</th> 
								<th data-field="country" data-sortable="true">Edit</th> 
								<th data-field="dateadded" data-sortable="true">Delete</th> 
						</tr>
						    
						    </thead>
						    <tbody> 
							{% for category in categories %}

							    <tr style="display:none;" data-index="0">
							    <td>{{ category.id }}</td>
							    <td style="">{{ category.title }}</td>
			<td><a href="edit-category.php?category={{ category.id }}" class="pencil"><svg class="glyph stroked pencil"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#stroked-pencil"></use></svg></a></td>
			<td><a href="delete/delete-category.php?category={{ category.id }}" onclick="return confirm('Are you sure you want to delete this category?');" class="trash"><svg class="glyph stroked trash"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#stroked-trash"></use></svg></a></td>

							    </tr>
							{% endfor %}
						    </tbody>
						</table>

					</div>
				</div>
			</div>


		
		</div><!-- /.col-->
<div class="col-lg-6">
				<div class="panel panel-default">
					<div class="panel-heading">Latest Posts</div>
					<div class="panel-body">
						<table data-toggle="table" >
						    <thead>
						    <tr>
								<th data-field="id"  data-sortable="true">ID</th> 
								<th data-field="title" data-sortable="true">Title</th> 
								<th data-field="edit">Edit</th> 
						</tr>
						    
						    </thead>
						    <tbody> 
							{% for post  in posts %}

							    <tr style="display:none;" data-index="0">
							    <td>{{ post.id }}</td>
							    <td style="">{{ post.title }}</td>
			<td>
			<a href="edit-post.php?post={{ post.id }}" class="pencil"><svg class="glyph stroked pencil"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#stroked-pencil"></use></svg></a>
			</td>


							    </tr>
							    	{% endfor %}
						    </tbody>
						</table>
					</div>
				</div>

</div>
		
		</div>


	</div>	<!--/.main-->
	<script type="text/javascript" src="template/default/assets/js/nicEdit.js"></script>
	<script type="text/javascript" src="template/default/assets/tinymce/tinymce.min.js"></script>
	<script type="text/javascript">
	tinymce.init({
	  selector: 'textarea',
	  height: 100,
	  plugins: [
	    'advlist autolink lists link image charmap print preview anchor',
	    'searchreplace visualblocks code fullscreen',
	    'insertdatetime media table contextmenu paste code'
	  ],
	  toolbar: 'insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image',
	  content_css: [
	    '//fast.fonts.net/cssapi/e6dc9b99-64fe-4292-ad98-6974f93cd2a2.css',
	    '//www.tinymce.com/css/codepen.min.css'
	  ]
	});	
	</script>
	<script src="template/default/assets/js/jquery-1.11.1.min.js"></script>
	<script src="template/default/assets/js/bootstrap.min.js"></script>
	<script src="template/default/assets/js/bootstrap-table.js"></script>	
	<script>
		!function ($) {
		    $(document).on("click","ul.nav li.parent > a > span.icon", function(){          
		        $(this).find('em:first').toggleClass("glyphicon-minus");      
		    }); 
		    $(".sidebar span.icon").find('em:first').addClass("glyphicon-plus");
		}(window.jQuery);

		$(window).on('resize', function () {
		  if ($(window).width() > 768) $('#sidebar-collapse').collapse('show')
		})
		$(window).on('resize', function () {
		  if ($(window).width() <= 767) $('#sidebar-collapse').collapse('hide')
		})
	</script>	
</body>

</html>