<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>New User - My Topic, My Opinion</title>
		
	<link href="template/default/assets/css/bootstrap.min.css" rel="stylesheet">
	<link href="template/default/assets/css/styles.css" rel="stylesheet">
		
	<!--Icons-->
	<script src="template/default/assets/js/lumino.glyphs.js"></script>
		
	<!--[if lt IE 9]>
	<script src="template/default/assets/js/html5shiv.js"></script>
	<script src="template/default/assets/js/respond.min.js"></script>
	<![endif]-->
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
	<div class="container-fluid">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#sidebar-collapse">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="#"><span>My Topic, My Opinion</span>Dashboard</a>
			<ul class="user-menu">
				<li class="dropdown pull-right">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown"><svg class="glyph stroked male-user"><use xlink:href="#stroked-male-user"></use></svg> {{ user }} <span class="caret"></span></a>
				<ul class="dropdown-menu" role="menu">
				<li><a href="settings.php"><svg class="glyph stroked gear"><use xlink:href="#stroked-gear"></use></svg> Settings</a></li>
				<li><a href="logout.php"><svg class="glyph stroked cancel"><use xlink:href="#stroked-cancel"></use></svg> Log Out</a></li>
				</ul></li>
			</ul>
		</div>							
	</div><!-- /.container-fluid -->
</nav>
		
<div id="sidebar-collapse" class="col-sm-3 col-lg-2 sidebar">
	<ul class="nav menu">
		<li><a href="index.php"><svg class="glyph stroked home"><use xlink:href="#stroked-home"></use></svg> Dashboard</a></li>
		<li><a href="posts.php"><svg class="glyph stroked app window with content"><use xlink:href="#stroked-app-window-with-content"></use></svg> All Posts</a></li>
		<li><a href="new-post.php"><svg class="glyph stroked pencil"><use xlink:href="#stroked-pencil"></use></svg> Add New</a></li>
		<li><a href="categories.php"><svg class="glyph stroked folder"><use xlink:href="#stroked-folder"></use></svg> Categories</a></li>
		<li><a href="comments.php"><svg class="glyph stroked empty-message"><use xlink:href="#stroked-empty-message"></use></svg> Comments</a></li>
		<li class="active"><a href="users.php"><svg class="glyph stroked male user"><use xlink:href="#stroked-male-user"></use></svg> Users</a></li>
		<li><a href="settings.php"><svg class="glyph stroked gear"><use xlink:href="#stroked-gear"></use></svg> Settings</a></li>
		<li><a href="logout.php"><svg class="glyph stroked cancel"><use xlink:href="#stroked-cancel"></use></svg> Log Out</a></li>
		<li role="presentation" class="divider"></li>
	</ul>

</div><!--/.sidebar-->
		
<div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">			
	<div class="row">
		<ol class="breadcrumb">
			<li><a href="index.php"><svg class="glyph stroked home"><use xlink:href="#stroked-home"></use></svg></a></li>
			<li class="active">New User</li>
		</ol>
	</div><!--/.row-->
				
		<div class="row">
		<div class="col-lg-12">
		<div class="panel panel-default">
		<div class="panel-heading">New User</div>
		<div class="panel-body">
		<div class="col-md-12">
		<form role="form"  enctype="multipart/form-data"  action="new-user.php"  method="post">
							
		<div class="form-group">
		<label>Username:</label>
		<input type="text" name="username" id="username" placeholder="Log In Username" class="form-control" required="required"/>
		</div>
		
		<div class="form-group">
		<label>Password:</label>
		<input type="password" name="password" id="password" placeholder="Log In Password" class="form-control" required="required"/>
		</div>

		<div class="form-group">
		<label>First Name:</label>
		<input type="text" name="firstname" id="firstname" placeholder="First Name" class="form-control" required="required"/>
		</div>	
		
		<div class="form-group">
		<label>Last Name:</label>
		<input type="text" name="lastname" id="lastname" placeholder="Last Name" class="form-control" required="required"/>
		</div>
		
		<div class="form-group">
		<label>E-Mail:</label>
		<input type="email" name="email" id="email" placeholder="E-Mail Address" class="form-control" required="required"/>
		</div>		


		<div class="form-group">
		<label>Phone Number:</label>
		<input type="text" name="phone" id="phone" placeholder="Phone Number" class="form-control" required="required"/>
		</div>
		
		<div class="form-group">
		<label>Country:</label>
		<input type="text" name="country" id="countr" placeholder="Country" class="form-control" required="required"/>
		</div>
		
		<div class="form-group">
		<label>City:</label>
		<input type="text" name="city" id="city" placeholder="City" class="form-control" required="required"/>
		</div>				
				
		<button type="submit" name="submit" class="btn btn-paleutism pull-right">Add User</button>
		</div>
		
		</form>
		</div>
		</div>
		</div><!-- /.col-->
		</div><!-- /.row -->
		
	</div><!--/.main-->
	
	<script type="text/javascript" src="template/default/assets/js/nicEdit.js"></script>
	<script type="text/javascript">
	bkLib.onDomLoaded(function() { nicEditors.allTextAreas() });
	new nicEditor({iconsPath : 'template/default/assets/js/nicEditorIcons.gif'}).panelInstance('description');
	</script>
	<script src="template/default/assets/js/jquery-1.11.1.min.js"></script>
	<script src="template/default/assets/js/bootstrap.min.js"></script>
</body>
</html>